export type FindTicketsResponse = {
  findTickets: Array<{
    ticketCode: string;
    issuerUserCode: string;
    issuerCompanyCode: string;
    recipientUserCode: string;
    recipientCompanyCode: string;
    name: string;
    description: string;
    method: string;
    queue: string;
    type: string;
    category: string;
    status: string;
    priority: string;
    sentMessage: string;
    duration: string;
    observation: string;
    responsibleCode: string;
    responsible: string;
    scheduledAt: string;
    rescheduledAt: string;
    finishedAt: string;
    messages: Array<{
      messageCode: string;
      sentUserCode: string;
      sentCompanyCode: string;
      receivedUserCode: string;
      receivedCompanyCode: string;
      nameSentUser: string;
      nameSentCompany: string;
      nameReceivedUser: string;
      nameReceivedCompany: string;
      title: string;
      email: string;
      phone: string;
      message: string;
      read: string;
      observation: string;
      createdAt: string;
      updatedAt: string;
      deletedAt: string;
    }>;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
  }>;
};
