export type StudentRegisterFormErrors = {
    nameError?: string,
    birthDateError?: string,
    codeError?: string,
    identityError?: string,
    genderError?: string,
    stateMaritalError?: string,
    professionError?: string,
    companyError?: string,
    addressError?: string,
    numberError?: string,
    complementError?: string,
    zipCodeError?: string,
    districtError?: string,
    cityError?: string,
    stateError?: string,
    periodicityCodeError?: string,
    paymentDayError?: string,
    modalitiesError?: string,
    statusModalityError?: string,
    detailsPlanError?: string,
    emailError?: string,
    descriptionError?: string,
    phoneError?: string,
    emergencyContactError?: string,
    emergencyPhoneError?: string,
    responsibleError?: string,
    financeResponsibleError?: string,
    indicationSearchError?: string,
    [key: string]: string | undefined;
}