export type AdminGymDrawerType = {
    Application: 'Application',
    StudentRegister: 'StudentRegister',
    ShortcutCreate: 'ShortcutCreate',
    ClassCreate: 'ClassCreate',
    VisitRegister: 'VisitRegister',
    ContactCreate: 'ContactCreate',
    ChatCreate: 'ChatCreate',
    NotificationCreate: 'NotificationCreate',
    EventCreate: 'EventCreate',
    AdvertisementCreate: 'AdvertisementCreate',
    PlanCreate: 'PlanCreate',
    MarketCreate: 'MarketCreate',
    SupplierRegister: 'SupplierRegister',
    ContributorRegister: 'ContributorRegister',
    UserRegister: 'UserRegister',
    GroupCreate: 'GroupCreate',
    HourCreate: 'HourCreate',
    PlanAlter: 'PlanAlter',
    ClassAlter: 'ClassAlter',
    ClassDetails: 'ClassDetails',
    EditStudent: 'EditStudent',
    TicketCreate: 'TicketCreate'
};