export type RendererModulesType =
  | "Home"
  | "Home"
  | "Partners"
  | "Admin"
  | "Security"
  | "Plans"
  | "Students"
  | "Classes"
  | "Finance"
  | "Integration"
  | "Dashboard"
  | "Programs"
  | "Profile"
  | "Profile"
  | "Application"
  | "Frequencies"
  | "Relationship"
  | "Products"
  | "Marketplace"
  | "Suppliers"
  | "Contributors"
  | "Settings"
  | "Company"
  | "Support"
  | "Personal"
  | "Nutritionist"
  | "Notifications"
  | "GroupAccess"
  | "Signature"
  | "PartnerDetails"
  | "Invoices"
  | "BrandAndEstablishment"
  | "BrandDetails"
  | "EstablishmentDetails";

export type GymManagementType = RendererModulesType;
