export const PaymentMapper: Record<string, { label: string; color: string, backgroundColor: string, icon: string }> = {
    PENDING: { label: 'Pendente', color: '#e9a807', backgroundColor: '#fff4d9', icon: 'LuClock9' },
    PAID: { label: 'Pago', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'FaRegCircleCheck' },
    FAILED: { label: 'Falhou', color: '#f14138', backgroundColor: '#fff4f3', icon: 'MdOutlineCancel' },
    REVERSED: { label: 'Reembolsado', color: '#008080', backgroundColor: '#eafaf7', icon: 'RiUserReceivedLine' },
    REWARDS_CREDIT: { label: 'iFlex Rewards', color: '#ff0336', backgroundColor: '#fff2f4', icon: 'SiFirewalla' },
    REVERSED_PENDING: { label: 'Reembolso Pendente', color: '#ff854c', backgroundColor: '#fff6f2', icon: 'LuClock9' },
    CANCELED: { label: 'Cancelado', color: '#5f6579', backgroundColor: '#f7faff', icon: 'TiCancel' },
    PARTIALLY_REVERSED: { label: 'Reembolso Parcial', color: '#3498db', backgroundColor: '#dceff68f', icon: 'GrDirections' },
    CARD: { label: 'Cartão', color: '#3498db', backgroundColor: '#dceff68f', icon: 'FaRegCreditCard' },
    PIX: { label: 'Pix', color: '#2ebdaf', backgroundColor: '#eefef2', icon: 'MdOutlinePix' },
    CASH: { label: 'Dinheiro', color: '#7ea257', backgroundColor: '#eefef2', icon: 'BiDollarCircle' },
    BANK_TRANSFER: { label: 'Transferência Bancária', color: '#334555', backgroundColor: '#eef3f7', icon: 'TbTransformFilled' },
    CHARGE: { label: 'Cobrança', color: '#334555', backgroundColor: '#eef3f7', icon: 'TbMessageDollar' },
    REGISTRATION: { label: 'Matrícula', color: '#2ebdaf', backgroundColor: '#eefef2', icon: 'TbUserCog' },
    PLAN: { label: 'Plano', color: '#ff0336', backgroundColor: '#fff2f4', icon: 'CgFileDocument' },
    SERVICE: { label: 'Serviço', color: '#e9a807', backgroundColor: '#fff4d9', icon: 'MdOutlineDesignServices' },
    RECEIPT: { label: 'Recebimento', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'FaHandHoldingDollar' },
    PAYMENT: { label: 'Pagamento', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'TbMoodDollar' },
    EXPENSE: { label: 'Despesa', color: '#d1572a', backgroundColor: '#f8e7e1', icon: 'FaFileInvoiceDollar' },
    TRANSFER: { label: 'Transferência', color: '#334555', backgroundColor: '#eef3f7', icon: 'TbTransactionDollar' },
    SALE: { label: 'Venda', color: '#3498db', backgroundColor: '#a7ace6', icon: 'MdOutlinePointOfSale' },
    PURCHASE: { label: 'Compra', color: '#4a5df9', backgroundColor: '#eaedff', icon: 'TbShoppingCartDollar' },
    COMPANY: { label: 'Presencial', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'TbShoppingCartDollar' },
    WEB: { label: 'Site', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'TbShoppingCartDollar' },
    MOBILE_APP: { label: 'Aplicativo', color: '#16ae6b', backgroundColor: '#eefef2', icon: 'TbShoppingCartDollar' },
};
