export const QueueMapper: Record<string, { label: string }> = {
    TRIAGE: { label: 'Triagem' },
    CUSTOMER_SUCCESS: { label: 'Customer Success' },
    CLOUD: { label: 'Cloud' },
    TECHNICAL_SUPPORT: { label: 'Suporte Técnico' },
    DEVELOPMENT: { label: 'Desenvolvimento' },
    FINANCIAL: { label: 'Financeiro' },
    HR: { label: 'Recursos Humanos' },
    AUDIT: { label: 'Auditoria' },
    MARKETPLACE: { label: 'Marketplace' },
    SALES: { label: 'Comercial & Vendas' },
    MARKETING: { label: 'Marketing' },
    OPERATIONS: { label: 'Operações' },
    MANAGEMENT: { label: 'Administração & Gestão' },
    LEGAL: { label: 'Jurídico' },
    SECURITY: { label: 'Segurança da Informação' },
    PROCUREMENT: { label: 'Compras & Fornecedores' },
    COMPLIANCE: { label: 'Compliance' },
    DATA_PRIVACY: { label: 'Proteção de dados e LGPD/GDPR' },
    PARTNERSHIPS: { label: 'Parcerias' },
    CUSTOMER_ONBOARDING: { label: 'Onboarding de Clientes' },
    TRAINING: { label: 'Treinamento' },
    INTEGRATION: { label: 'Integrações' },
    SUPPLIER_SUPPORT: { label: 'Atendimento & Suporte' },
    GYM_SUPPORT: { label: 'Atendimento & Suporte' },
    PERSONAL_SUPPORT: { label: 'Atendimento & Suporte' },
    STUDENT_SUPPORT: { label: 'Atendimento & Suporte' },
    NUTRITIONIST_SUPPORT: { label: 'Atendimento & Suporte' },
    CUSTOMER_RETENTION: { label: 'Retenção de Clientes' },
    IT_INFRASTRUCTURE: { label: 'Infraestrutura de TI' },
    PRODUCT_SUPPORT: { label: 'Atendimento & Suporte' },
    QUALITY_ASSURANCE: { label: 'Garantia de Qualidade' },
    REGULATORY_AFFAIRS: { label: 'Assuntos Regulatórios' },
    LEGAL_COMPLIANCE: { label: 'Conformidade Legal' },
    PARTNER_SUPPORT: { label: 'Suporte a Parceiros' },
    INNOVATION: { label: 'Inovação' },
    AI_AUTOMATION: { label: 'Automação e IA' },
    RISK_MANAGEMENT: { label: 'Gestão de Riscos' },
    CUSTOMER_EDUCATION: { label: 'Retenção' },
    FACILITIES: { label: 'Gestão de Infraestrutura' },
    DATA_ANALYTICS: { label: 'Análise de Dados' },
    GOVERNANCE: { label: 'Governança' },
    INTERNAL_SUPPORT: { label: 'Suporte Interno' },
    ESG: { label: 'Sustentabilidade (ESG)' },
    FIELD_SERVICES: { label: 'Serviços de Campo' },
    EVENTS: { label: 'Eventos' },
    LOGISTICS: { label: 'Logística' },
    USERS: { label: 'Usuários' },
    SYSTEM: { label: 'Sistema' },
    PERFORMANCE: { label: 'Performance' },
    APP: { label: 'Aplicativo' },
};