export enum OriginEnum {
  POINT_OF_SALES = "POINT_OF_SALES",
  MOBILE_APP = "MOBILE_APP",
  ECOMMERCE = "ECOMMERCE",
  PARTNERS_ECOMMERCE = "PARTNERS_ECOMMERCE",
  INDUSTRY = "INDUSTRY",
  GRAPHQL = "GRAPHQL",
  PORTAL = "PORTAL",
  INTEGRATION = "INTEGRATION",
  WEBHOOK = "WEBHOOK",
  SYSTEM = "SYSTEM",
}
